### ISSUE TITLE
关于0x05无法运行

### ISSUE THREAD

**Issue by shiwei819** [WriteCode-ChangeWorld/Tools#3]
---------------------------------------------------------------------------------------
[2021-08-07 17:55:03] 网络请求出错 url:https://ca.gca.tw/page/1
Traceback (most recent call last):
File "C:\Users\Mizuhashi\github\tool_1\0x05-绅士小站\gca.py", line 216, in
gca.main()
File "C:\Users\Mizuhashi\github\tool_1\0x05-绅士小站\gca.py", line 113, in main
obj = etree.HTML(net_requests(options={"url":page_url}).text)
AttributeError: 'NoneType' object has no attribute 'text'
--------------------------------------------------------------------------------------
我按步骤弄了下，但说是无法访问了
或许我哪里搞错了吗

**Comment by Coder-Sakura** [comment]
站长已经停止维护了，站点进入无限期维护详情参考 https://cangku.io/archives/188182

**Comment by Coder-Sakura** [comment]
如果需要之前的绅士小站的资源留档，可以使用以下我生成的秒传链接（截止到21.6.16的资源留档，一共304部60G左右，封面图片也在其中）（60个压缩分卷）

fd0204242ca133060d19227f39eadbb0#c41ef049e1ecd8c758bcb5349519aa73#1048576000#绅士小站.z01
d954161e3dd3dce1ff96e7429ff5b53c#0e847bd1350c6ed71791c316330a2267#1048576000#绅士小站.z02
273564971f7f6ac6d02260a84568e52b#1d369a1a9e02f02c8a3daa3f485a1c91#1048576000#绅士小站.z03
ab27c3e6621cb6cf99009e207f49c1b1#cb0d5bdb91cc579033f0965244a61ef2#1048576000#绅士小站.z04
56dddce8b684ce187560efab79ba0ca9#6f240547ca0f3dbe9c6cb0dfed462e20#1048576000#绅士小站.z05
bda62c88212abc3a17e4266b30120b3b#b42cadcc1d6c6f0304c0e0f9411c3657#1048576000#绅士小站.z06
71cc248717bf77bb2e5611a94330a954#c0ed867d773f5e91523a7b328de49b3b#1048576000#绅士小站.z07
f7c672e38794d8c34e0977e68254b95e#ad96d3a946ecbdc521d734630c989cbc#1048576000#绅士小站.z08
83b32014bc8075d1734a5cabf45661a1#b7f523075c84875a687a76655d04d835#1048576000#绅士小站.z09
8545fba1720d1cb6d405f73420d59ea2#bfd4895f354fefef890440aeb5d16e02#1048576000#绅士小站.z10
3fa091eff40eb5c800bb600541af814e#9258f51f45abbbd903fb0b64990cc619#1048576000#绅士小站.z11
f486ae2afbde35a29124ea4da8a7f6e9#0f30670e21db6b34242413220c909879#1048576000#绅士小站.z12
03333741421f33f0b4f9537474119512#6776305e8ec98ab2dba7eb2537cd2612#1048576000#绅士小站.z13
a62c82c70b0d1596442fa07a02df4123#f25f191e3b4d15f8d76109bf8fc5ea53#1048576000#绅士小站.z14
f45bcddbd1823369b1445e64476f9f13#86d33576577397eb71bd2b9d76022722#1048576000#绅士小站.z15
19054c705642869d7c5ea3c8a128df5d#ada03d7625064a11f8f57f4f4cb87357#1048576000#绅士小站.z16
17c891a81e09fe743b150308766f21ed#41f26ddc0588806c8acb364381e8b68f#1048576000#绅士小站.z17
3999cb13a2b64bb6412f3d75b4c89d62#21f5bad6e7270192cebd1f58db448678#1048576000#绅士小站.z18
27a9805d955d5ad837b66ba0894fe041#aea980cae788e35ea2c7d36dd69cf358#1048576000#绅士小站.z19
43d1b7e6cbb3e68044ea65969b0717f0#ae6b8a5e21eb7deb518f902d53147b13#1048576000#绅士小站.z20
02cf82191ab241804ca0fe43b740f9e3#691a20fcf1021facad1271d458c9307c#1048576000#绅士小站.z21
cf1b94f92878118ee037a4f055cdf18b#5520e9da70fbf21fcad759ff4c5503fd#1048576000#绅士小站.z22
abb6a8bcdf4dab5ed3a3881ddc0db9d2#1e3ea730a30988efb5bc7110be082a39#1048576000#绅士小站.z23
029b966e8cd7663520c3ecf1217980cc#9d6336a141355df06d2da8b07b24b201#1048576000#绅士小站.z24
f04df2f0f8b0c92bd8a2c33e4b83c278#7102ba65ac49c7a89ff4f189ede21be7#1048576000#绅士小站.z25
8d45dc29843cfa7e3c6ed2132f2f32e3#0523aed50cd015bf5d6fadfc0ab05c46#1048576000#绅士小站.z26
3d67a5f0e17086568235550773eb1a68#717db60f6f2291be89c2d399b2e25ffd#1048576000#绅士小站.z27
6075b2bd1b032e9f7b3cc7a3a0d0eb19#d3b98e6a17c8b8985422625c5b5462fb#1048576000#绅士小站.z28
b5b72d489bbdcb6afc6f37bb65c858ed#296c17c725b0aa9cc489e2458c9a6fac#1048576000#绅士小站.z29
0f0bd9d1ff6143d24d75ca02051c3559#42b9f9bd518f9ac6446d87e02656132e#1048576000#绅士小站.z30
b143bc53a4999fbe3eccdafe92cd7a03#e082d2eedffe1a82a2ed04c9472df5c6#1048576000#绅士小站.z31
3e969b70b43f2668047997eb8e98478e#8beaecdc168ed2e33363362fe355c51e#1048576000#绅士小站.z32
e2083888f87f3f9434754dda74948cbf#018239c02d4c7f460029a5ad9fae8ce3#1048576000#绅士小站.z33
cdebe2e757b3f558d47354df1c6c9566#d39ec33a4afd1b78d038bfac034b5228#1048576000#绅士小站.z34
ea5ff6bb7afd96558318e55813fce382#3824f3203b4ed4fc654f17af36e76810#1048576000#绅士小站.z35
17d59f9429497a45bfcf1363d04bd7f0#00531662e659a097eb5036d4efbf9847#1048576000#绅士小站.z36
3f27d48fcb81064685d1a05eacb3830e#88e9c14673591c18755c07671874da95#1048576000#绅士小站.z37
45df41bf689a9ea9a68fea0992c605e5#380cd900be8108de7f0de3ea58f8d048#1048576000#绅士小站.z38
8ac5bd81af537efa62997ef7a30506ba#51b5396568a487c1ad9b3adebd722a15#1048576000#绅士小站.z39
1a90e7621dd01a1b0edb52013ab42131#9c1408dc922e4f346ab7fc33195c0021#1048576000#绅士小站.z40
ea35101504e81387154c278deaa0ee83#937171755b990ec762d1efd3298db37d#1048576000#绅士小站.z41
c39798647a05cd6e0e57d8e1e7869e47#873eb02e34140743c6f99c61b08fbb51#1048576000#绅士小站.z42
ebc1031b8828b0d75cdf67ee035e1e63#e8e0832f020f5acd8e6f4c2f0872d3a2#1048576000#绅士小站.z43
d75ed54f62069c386cd9e60c50eadef7#1eebee6cac2c93eb3ba88f5873584c3f#1048576000#绅士小站.z44
78828f9885b93d61ca1a85a1638976a0#591694d65fc55ee1124fe29095ccbb63#1048576000#绅士小站.z45
edda6eaebbe30b54d48fd53a735008ca#b56e28cdfdc1ac5bd196c656a78cefa0#1048576000#绅士小站.z46
12bc2854216398947710be8e27993673#ce79ca00d090ef819fb5a9247cc1c2f0#1048576000#绅士小站.z47
188f13eeeb374ff20bbd3b45fef8f3c0#2463635cf0c00f8243ff9f453cf1c5d1#1048576000#绅士小站.z48
473c486a22e785c60417f7bbfba6f710#d39b5a89b0bc6333594ddbdced22ae03#1048576000#绅士小站.z49
afb706c3f669e2a5b4d229d49962a56e#5e8ae0d9542025d8120aa48be27eb51a#1048576000#绅士小站.z50
e8e1d9a7f4937759126e083355c71b3c#4186330818f70c1779d49c934719e6c5#1048576000#绅士小站.z51
32f073dad58c946d78c1db210a51c960#f8f6b2891fdad256df9de5f6e79c3727#1048576000#绅士小站.z52
42c2c828f2925ded319f3cf5e0d8c83c#25bc712595e2ee2259c953a0f74dfc9e#1048576000#绅士小站.z53
aba517edce8312719299287dbb86fb37#806105f8d3458c4e91e57f74f46a659f#1048576000#绅士小站.z54
968a3353693b24cb7489c338f4f1d0e4#67e05aa436d1560331d6470d4464e6d4#1048576000#绅士小站.z55
fb0f8156e6e1e8bdeec13cd722867ed0#10df8f5025e0cd249fb8f85876d4f903#1048576000#绅士小站.z56
be632a1c50ee1571affd5abe24e98021#1d1c235f2d31026090903a54389b98a3#1048576000#绅士小站.z57
7ef8d43e0d4d1bf3cba286d4f41f8856#fadbac43dc6b717c72e8d1cd43713007#1048576000#绅士小站.z58
e037dd47bfd2ea0bd66931970b8b9e5a#90c49c1fdb483c2ef492ca56ea125686#1048576000#绅士小站.z59
78630a8ecc5b74b3be53d31e5eac2652#1e7d99abc8f6834c95f4d3b522beaae1#38618071#绅士小站.zip
