### ISSUE TITLE
0x03下载问题

### ISSUE THREAD

**Issue by ldz14** [WriteCode-ChangeWorld/Tools#4]
如果作者的作品数量较多，页数超过2页时，只会下载第一页和最后一页，中间都被跳过

**Comment by Coder-Sakura** [comment]
@ldz14 给个问题链接测试下。我使用的这个链接是可以全部下载的。
[这腿借WO玩一天](https://ecchi.iwara.tv/users/%E8%BF%99%E8%85%BF%E5%80%9Fwo%E7%8E%A9%E4%B8%80%E5%A4%A9)

**Comment by 5ee1e** [comment]
hm... I'm having the same problem.
The following are the [RindouMMD](https://ecchi.iwara.tv/users/rindoummd) I referred to, there should be close to 200, but only 56 are actually retrieved
This is the first page and one of the remaining
![image](https://user-images.githubusercontent.com/48326733/141135852-354d785f-f03f-4afc-a850-18a5588ab9c5.png)

**Comment by Coder-Sakura** [comment]
@ldz14 @L4Ph 
---
感谢发现Bug！V1.0.4版本已修复，请使用最新版本。
最新版本加入了loguru，需要重新执行pip install -r requirement.txt进行安装依赖

Thanks for finding the bug! V1.0.4 version has been fixed, please use the latest version
The latest version has joined <loguru>, you need to re-execute <pip install -r requirement.txt> to install dependencies
