### ISSUE TITLE
0x03 作者作品不足一页时报错

### ISSUE THREAD

**Issue by 603185423** [WriteCode-ChangeWorld/Tools#5]
测试连接：https://ecchi.iwara.tv/users/%E3%83%8F%E3%83%9E%E3%82%88%E3%82%8A
`2021-12-08 17:46:14.589 | INFO     | __main__:__init__:94 - 输入链接数量 - 1`
`2021-12-08 17:46:24.861 | INFO     | __main__:get_links:204 - User Have 8 Videos. Not Video Page`
`2021-12-08 17:46:24.864 | WARNING  | __main__:main:414 - Exception - local variable 'total_pageNum' referenced before assignment`
`PS E:\iwara> .\iwara.py`
在205行添加total_pageNum = -1即可解决（？）

**Comment by Coder-Sakura** [comment]
非常感谢，最新版本已修复。这是更新v1.0.4时的一个遗漏问题
