### ISSUE TITLE
0x03 希望可以增加视频完整性校验

### ISSUE THREAD

**Issue by 603185423** [WriteCode-ChangeWorld/Tools#6]
有时候由于网络波动（可能？），视频下载不完整，希望可以增加视频完整性校验，能够在视频下载完成后自动删除校验失败的视频（要是能自动重试若干次就更好了XD）
目前我了解到的方式可以通过调用ffmpeg
`ffmpeg -v error -i "123.MP4" -map 0:0 -f null - 2> "123.log"`
若是视频中含有错误，.log文件中会有错误信息；反之，则生成一个0字节的.log文件

**Comment by Coder-Sakura** [comment]
- 说下我的想法。简单校验一下的话，可以在下载完成后校验视频字节数与响应头里的字节数.
  校验失败的视频放在程序执行完毕后进行重试，超出重试次数则保存视频链接到单独的log内供用户查看.

- ffmpeg的话，我还没怎么用过，暂时保留。有时间的话，我先去了解一下

**Comment by 603185423** [comment]
那应该对比字节数是更优的解决方案，我遇到的所有（应该是所有）视频下载有错误都是字节数对不上的
用ffmpeg只是我能找到的下策，一个200mb的视频要至少10s才能校验完成(i5-8300H100%占用)(
