### ISSUE TITLE
0x03 一些关于视频标题的问题

### ISSUE THREAD

**Issue by Ai-desu-2333** [WriteCode-ChangeWorld/Tools#9]
在使用时发现一些视频的标题会被截断或忽略一些特殊字符，导致出现一些问题，如：

- 标题过长被截断：

  原视频标题：
  `【お仕置き的な】リンちゃんに電気あんまされたり色々やらされるミクさん　～前編～ 【punish】Miku being punished by Rin　 ～Prequel～`
  解析及下载标题：
  `【お仕置き的な】リンちゃんに電気あんまされたり色々や--aglknfoejs75xe80`
  [源视频链接](https://ecchi.iwara.tv/videos/aglknfoejs75xe80)
  [作者链接](https://ecchi.iwara.tv/users/kojirou)
  
  原视频标题：
  `【お仕置き的な】リンちゃんに電気あんまされたり色々やらされるミクさん　～中編～ 【punish】Miku being punished by Rin　～ sequel_1～`
  解析及下载标题：
  `【お仕置き的な】リンちゃんに電気あんまされたり色々やら--jp3kqf38yseaoj1q`
  [源视频链接](https://ecchi.iwara.tv/videos/jp3kqf38yseaoj1q)
  [作者链接](https://ecchi.iwara.tv/users/kojirou)
  
  原视频标题：
  `【友情の輪】ラブライブ3人娘part１【検索犬】[Friendship Circle] Love Live 3 Girls part 1 [Search Dog] [Hypnosis]`
  解析及下载标题：
  `【友情の輪】ラブライブ3人娘part１【検索犬】[Fr--r4lqlsw9jtoeen97`
  [源视频链接](https://ecchi.iwara.tv/videos/r4lqlsw9jtoeen97)
  [作者链接](https://ecchi.iwara.tv/users/%E6%A4%9C%E7%B4%A2%E7%8A%AC)
- 空格，“ / ” 等特殊字符被忽略：

  原视频标题：
  `【原神/genshin impact】神里凌华/kamisato ayaka`
  解析及下载标题：
  `【原神genshinimpact】神里凌华kam--aqpbrs18ji7xjbbw`
  [源视频链接](https://ecchi.iwara.tv/videos/aqpbrs18ji7xjbbw)
  [作者链接](https://ecchi.iwara.tv/users/someru%E9%85%B1)

  原视频标题：
  `【原神/genshin impact】九条裟罗 / Kujou Sara`
  解析及下载标题：
  `【原神genshinimpact】九条裟罗K--aklqrc18ji7wl2vw`
  [源视频链接](https://ecchi.iwara.tv/videos/aklqrc18ji7wl2vw)
  [作者链接](https://ecchi.iwara.tv/users/someru%E9%85%B1)
  
  原视频标题：
  `bl68竖屏【刻晴】Hi-Fi ravea`
  解析及下载标题：
  `bl68竖屏【刻晴】Hi-Firavea--8gb2eh7ye9slnja6k`
  [源视频链接](https://ecchi.iwara.tv/videos/8gb2eh7ye9slnja6k)

  原视频标题：
  `bl58 布料【言和】Good-night-kiss`
  解析及下载标题：
  `bl58布料【言和】Good-night-kiss--od479u2gwku1jy87y`
  [源视频链接](https://ecchi.iwara.tv/videos/od479u2gwku1jy87y)

前者经测试只有在下载某作者所有视频（即输入链接为`https://ecchi.iwara.tv/users/XXX`）时会出现，判断是Iwara作者视频页的标题进行了省略，导致获取的标题出了问题。
 [検索犬](https://ecchi.iwara.tv/users/%E6%A4%9C%E7%B4%A2%E7%8A%AC/videos)
 ![image](https://user-images.githubusercontent.com/61218958/169708851-c17ecc98-a1f4-45d9-90ff-3543f5218397.png)
 暂时没找到解决方法。（或者说不知道应该怎么改）

- 后者解决方法：
将188-190行
```
title = re.sub('[\/:*?"<>|]','',r)
title = title.replace("&amp;","&").replace("\u3000","")\.
				replace(" ","").replace(".","")
```
 改为
```
title = re.sub('[\/:*?"<>|]','_',r)
title = title.replace("&amp;","&").replace("\u3000","_").\
				replace(" ","_").replace(".","_")
```
将所有特殊字符从“吃掉”改为替换成`_`解决了此问题。
  原视频标题：
`【原神/genshin impact】九条裟罗 / Kujou Sara`
  修改后解析及下载标题：
`【原神_genshin_impact】九条裟罗___Kujou_Sara--aklqrc18ji7wl2vw`
但在Windows环境下，我认为其他特殊字符替换为`_`，空格仍保持空格会更加合适。

**Comment by Coder-Sakura** [comment]
这部分内容可以作为优化的一部分，下班之后我找个时间看看

**Comment by Coder-Sakura** [comment]
> 在使用时一些视频的标题会截断或出现一些特殊现象，会导致一些问题，例如：
> 
> * 标题过长被截断：
>   原视频标题：
>   `【お仕置き的な】リンちゃんに電気あんまされたり色々やらされるミクさん　～前編～ 【punish】Miku being punished by Rin　 ～Prequel～`
>   解析及下载标题：
>   `【お仕置き的な】リンちゃんに電気あんまされたり色々や--aglknfoejs75xe80`
>   [源视频链接](https://ecchi.iwara.tv/videos/aglknfoejs75xe80)
>   [作者链接](https://ecchi.iwara.tv/users/kojirou)
>   原视频标题：
>   `【お仕置き的な】リンちゃんに電気あんまされたり色々やらされるミクさん　～中編～ 【punish】Miku being punished by Rin　～ sequel_1～`
>   解析及下载标题：
>   `【お仕置き的な】リンちゃんに電気あんまされたり色々やら--jp3kqf38yseaoj1q`
>   [源视频链接](https://ecchi.iwara.tv/videos/jp3kqf38yseaoj1q)
>   [作者链接](https://ecchi.iwara.tv/users/kojirou)
>   原视频标题：
>   `【友情の輪】ラブライブ3人娘part１【検索犬】[Friendship Circle] Love Live 3 Girls part 1 [Search Dog] [Hypnosis]`
>   解析及下载标题：
>   `【友情の輪】ラブライブ3人娘part１【検索犬】[Fr--r4lqlsw9jtoeen97`
>   [源视频链接](https://ecchi.iwara.tv/videos/r4lqlsw9jtoeen97)
>   [作者链接](https://ecchi.iwara.tv/users/%E6%A4%9C%E7%B4%A2%E7%8A%AC)
> * 空格，“ / ” 等特殊字符被发射：
>   原视频标题：
>   `【原神/genshin impact】神里凌华/kamisato ayaka`
>   解析及下载标题：
>   `【原神genshinimpact】神里凌华kam--aqpbrs18ji7xjbbw`
>   [源视频链接](https://ecchi.iwara.tv/videos/aqpbrs18ji7xjbbw)
>   [作者链接](https://ecchi.iwara.tv/users/someru%E9%85%B1)
>   原视频标题：
>   `【原神/genshin impact】九条裟罗 / Kujou Sara`
>   解析及下载标题：
>   `【原神genshinimpact】九条裟罗K--aklqrc18ji7wl2vw`
>   [源视频链接](https://ecchi.iwara.tv/videos/aklqrc18ji7wl2vw)
>   [作者链接](https://ecchi.iwara.tv/users/someru%E9%85%B1)
>   原视频标题：
>   `bl68竖屏【刻晴】Hi-Fi ravea`
>   解析及下载标题：
>   `bl68竖屏【刻晴】Hi-Firavea--8gb2eh7ye9slnja6k`
>   [源视频链接](https://ecchi.iwara.tv/videos/8gb2eh7ye9slnja6k)
>   原视频标题：
>   `bl58 布料【言和】Good-night-kiss`
>   解析及下载标题：
>   `bl58布料【言和】Good-night-kiss--od479u2gwku1jy87y`
>   [源视频链接](https://ecchi.iwara.tv/videos/od479u2gwku1jy87y)
> 
> 曾经的测试只有在下载某个作者的所有视频（即输入为`https://ecchi.iwara.tv/users/XXX`）时会出现，是岩原作者鉴定页的标题进行了省略的视频，正在获取的标题链接。 [検索犬](https://ecchi.iwara.tv/users/%E6%A4%9C%E7%B4%A2%E7%8A%AC/videos) 暂时没有解决方法。（或者找到说不知道应该怎么改） ![图片](https://user-images.githubusercontent.com/61218958/169708851-c17ecc98-a1f4-45d9-90ff-3543f5218397.png)
> 
> * 上一个解决方法：
>   将188-190行
> 
> ```
> title = re.sub('[\/:*?"<>|]','',r)
> title = title.replace("&amp;","&").replace("\u3000","")\.
> 				replace(" ","").replace(".","")
> ```
> 
> 改为
> 
> ```
> title = re.sub('[\/:*?"<>|]','_',r)
> title = title.replace("&amp;","&").replace("\u3000","_").\
> 				replace(" ","_").replace(".","_")
> ```
> 
> 将所有特殊情况从“吃掉”替换 成 修改 问题`_`。。 `【原神/genshin impact】九条裟罗 / Kujou Sara` `【原神_genshin_impact】九条裟罗___Kujou_Sara--aklqrc18ji7wl2vw``_`

还有个问题，请问是直接copy 视频链接进行下载的吗？还是复制作者的视频主页？
![image](https://user-images.githubusercontent.com/40787018/169784452-2269b4a0-a674-4895-97c9-a5a113926bfd.png)

**Comment by Ai-desu-2333** [comment]
> 
> 还有个问题，请问是直接复制视频进行下载的吗？ ![图片](https://user-images.githubusercontent.com/40787018/169784452-2269b4a0-a674-4895-97c9-a5a113926bfd.png)

第一种情况是直接输入作者的主页`https://ecchi.iwara.tv/users/xxx`进行下载才出现的；
输入视频链接`https://ecchi.iwara.tv/videos/xxx`进行下载能下载到完整标题。

第二种情况则是两种链接都会出现。

**Comment by Coder-Sakura** [comment]
@Ai-desu-2333 感谢反馈，问题已修复。

1. 问题：`标题过长被截断`

原因：作者主页给出的视频标题长度有限
应对：

- 无videos页面的作者，通过访问作品视频页面获取`title`
- 有videos页面的作者，更改xpath表达式为`.//div[@class='field-item even']/a/img/@title`进行匹配

---
2. 问题：`空格，“ / ” 等特殊字符被忽略`

原因：
应对：根据建议：特殊字符替换为`_`，空格保留
